name: "publish"
on:
  release:
    types: [published]

jobs:
  changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      changelog: ${{ steps.changelog.outputs.changelog }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Build Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v6
        with:
          mode: "COMMIT"
          toTag: ${{ github.event.release.tag_name }}
          configuration: ".github/changelog-config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Release
        uses: softprops/action-gh-release@v3
        with:
          body: ${{ steps.changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract Tag version
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          echo "VERSION=${VERSION#v}" >> $GITHUB_ENV

      - name: Update Files
        run: |
          pnpm version ${VERSION} --no-git-tag-version
          sed -i -E "s/(\"version\": \")[^\"]*(\")/\1${VERSION}\2/g" src-tauri/tauri.conf.json

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update file versions to ${{ env.VERSION }}"
          branch: main
          file_pattern: "package.json src-tauri/tauri.conf.json"

  release-github:
    name: release to github (${{ matrix.platform }} ${{ matrix.args }})
    needs: changelog
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # ARM Based macs
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest"
            args: "--target x86_64-apple-darwin" # Intel Based Macs
          - platform: "ubuntu-latest"
            args: ""
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v7

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev patchelf libxdo-dev libssl-dev

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: 10
          cache: true

      - name: install frontend dependencies
        run: pnpm install

      - name: build and upload assets to github release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ${{ matrix.args }}

  release-snap:
    needs: changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: snapcore/action-build@v1
        id: build
      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: stable
